# Generated by Django 3.2.12 on 2022-06-23 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.encrypt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_user_user_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.CharField(db_index=True, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.CharField(choices=[('PAGERDUTY', 'PagerDuty'), ('SLACK', 'Slack')], max_length=32)),
                ('displayable', models.CharField(max_length=140)),
                ('auth', utils.encrypt.fields.EncryptedCharField(max_length=2056)),
                ('meta', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='authentication.workspace')),
            ],
            options={
                'db_table': 'integration_config',
                'unique_together': {('workspace', 'integration', 'displayable')},
            },
        ),
    ]
