# Generated by Django 2.2.6 on 2020-06-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200605_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
