version: "3.4"
x-sqlserver-defaults: &sqlserver_defaults
  environment:
    ACCEPT_EULA: "Y"
services:
  database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metamapper
    restart: unless-stopped
  metamapper:
    build: ../../../
    image: metamapper:inspector
    environment:
      METAMAPPER_DB_HOST: database
      METAMAPPER_CELERY_RESULT_BACKEND: "amqp"
      METAMAPPER_FERNET_KEY: mHYPeDvFJ1LtDClYGtckO-PZCBZfM2xLpWKqu7qQSkI=
    depends_on:
      - database
  sqlserver-2017:
    build:
      context: ./
      args:
        MSSQL_IMAGE: mcr.microsoft.com/mssql/server
        MSSQL_VERSION: 2017-CU21-ubuntu-16.04
    << : *sqlserver_defaults
  sqlserver-2019:
    ports:
      - "1433:1433"
    build:
      context: ./
      args:
        MSSQL_IMAGE: mcr.microsoft.com/mssql/server
        MSSQL_VERSION: 2019-CU5-ubuntu-16.04
    << : *sqlserver_defaults
