version: '3.4'
x-restart-policy: &restart_policy
  restart: unless-stopped
x-metamapper-defaults: &metamapper_defaults
  << : *restart_policy
  image: metamapper
  env_file:
    - .env
  depends_on:
    - database
  networks:
    - metamapper
  volumes:
    - ./:/usr/local/metamapper
services:
  database:
    << : *restart_policy
    image: postgres:9.6
    ports:
      - 5430:5432
    volumes:
      - metamapper-database:/var/lib/postgresql/data
    networks:
      - metamapper
    environment:
      POSTGRES_PASSWORD: postgres
  msgbroker:
    << : *restart_policy
    image: redis:alpine
    networks:
     - metamapper
  webserver:
    << : *metamapper_defaults
    build:
      context: ./
    command: webserver
    ports:
      - 5050:5050
  worker:
    << : *metamapper_defaults
    command: worker --concurrency=1
    depends_on:
      - database
      - msgbroker
  scheduler:
    << : *metamapper_defaults
    command: scheduler
    depends_on:
      - database
      - msgbroker
volumes:
  metamapper-database:
    driver: local
networks:
  metamapper:
    driver: bridge
