version: '3.4'
x-restart-policy: &restart_policy
  restart: unless-stopped
services:
  database:
    << : *restart_policy
    image: postgres:9.6
    ports:
      - 5430:5432
    volumes:
      - metamapper-database:/var/lib/postgresql/data
    networks:
      - metamapper
    environment:
      POSTGRES_PASSWORD: postgres
  rabbitmq:
    << : *restart_policy
    image: rabbitmq:3.6
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
     - metamapper
  webserver:
    << : *restart_policy
    env_file:
      - .env
    image: metamapper
    command: webserver
    volumes:
      - ./:/usr/local/metamapper
    ports:
      - 5050:5050
    depends_on:
      - database
    networks:
      - metamapper
  worker:
    << : *restart_policy
    env_file:
      - .env
    image: metamapper
    command: worker
    depends_on:
      - database
      - rabbitmq
    volumes:
      - ./:/usr/local/metamapper
    networks:
      - metamapper
  scheduler:
    << : *restart_policy
    env_file:
      - .env
    image: metamapper
    command: scheduler
    depends_on:
      - database
      - rabbitmq
    volumes:
      - ./:/usr/local/metamapper
    networks:
      - metamapper
  redis:
    << : *restart_policy
    image: redis:alpine
    networks:
     - metamapper
volumes:
  metamapper-database:
    driver: local
networks:
  metamapper:
    driver: bridge
