version: '3.4'
x-restart-policy: &restart_policy
  restart: unless-stopped
x-metamapper-defaults: &metamapper_defaults
  << : *restart_policy
  image: metamapper
  environment:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
    - AWS_SECURITY_TOKEN=$AWS_SECURITY_TOKEN
    - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
  env_file:
    - .env
  depends_on:
    - database
    - elastic
  networks:
    - metamapper
  volumes:
    - ./:/usr/local/metamapper
services:
  database:
    << : *restart_policy
    image: postgres:9.6
    ports:
      - 5430:5432
    volumes:
      - metamapper-database:/var/lib/postgresql/data
    networks:
      - metamapper
    environment:
      POSTGRES_PASSWORD: postgres
  elastic:
    << : *restart_policy
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - metamapper
    environment:
      discovery.type: single-node
  msgbroker:
    << : *restart_policy
    image: redis:alpine
    networks:
     - metamapper
  webserver:
    << : *metamapper_defaults
    build:
      context: ./
    command: webserver
    ports:
      - 5050:5050
  worker:
    << : *metamapper_defaults
    command: worker --concurrency=1
    depends_on:
      - database
      - msgbroker
  scheduler:
    << : *metamapper_defaults
    command: scheduler
    depends_on:
      - database
      - msgbroker
volumes:
  metamapper-database:
    driver: local
networks:
  metamapper:
    driver: bridge
