# Generated by Django 3.0.10 on 2022-03-09 19:04

from django.db import migrations, models
import django.db.models.deletion
import utils.mixins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('definitions', '0001_initial'),
        ('authentication', '0003_workspace_active_sso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.CharField(db_index=True, default=utils.mixins.models.uuid4_hex, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the run was created.')),
                ('started_at', models.DateTimeField(default=None, help_text='Timestamp for when run queued actual processing tasks.', null=True)),
                ('finished_at', models.DateTimeField(default=None, help_text='Timestamp for when run finished calculating all revisions.', null=True)),
                ('datastore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_history', to='definitions.Datastore')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_history', to='authentication.Workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_task_id', models.CharField(help_text='Task ID for Celery', max_length=512, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('REVOKED', 'REVOKED')], default='PENDING', max_length=10)),
                ('error', models.TextField(null=True)),
                ('started_at', models.DateTimeField(default=None, help_text='Timestamp for when the task started', null=True)),
                ('finished_at', models.DateTimeField(default=None, help_text='Timestamp for when the task finished', null=True)),
                ('storage_path', models.CharField(max_length=512, unique=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='revisioner.Run')),
            ],
        ),
    ]
