# Generated by Django 3.0.7 on 2020-07-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisioner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionererror',
            name='exc_message',
            field=models.TextField(default=None, null=True),
        ),
    ]
