# Generated by Django 3.0.8 on 2020-08-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisioner', '0002_revisionererror_exc_message'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='revision',
            name='unique_revision_checksum',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='checksum',
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('workspace_id', 'revision_id'), name='unique_revision_checksum'),
        ),
    ]
