# Generated by Django 3.0.10 on 2022-03-09 18:58

import app.authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import utils.delete.managers
import utils.encrypt.fields
import utils.mixins.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('sub', models.CharField(default=None, max_length=128, null=True, unique=True)),
                ('sso_access_token', utils.encrypt.fields.EncryptedCharField(default=uuid.uuid4, help_text='One-time token used for SSO flows', max_length=40, null=True)),
                ('sso_access_token_issued_at', models.DateTimeField(default=None, null=True)),
                ('google_oauth2_token', utils.encrypt.fields.EncryptedCharField(default=None, max_length=128, null=True)),
                ('google_oauth2_token_issued_at', models.DateTimeField(default=None, null=True)),
                ('github_oauth2_token', utils.encrypt.fields.EncryptedCharField(default=None, max_length=50, null=True)),
                ('github_oauth2_token_issued_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'auth_users',
            },
            managers=[
                ('objects', app.authentication.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(db_index=True, default=utils.mixins.models.uuid4_hex, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ssh_private_key', utils.encrypt.fields.EncryptedTextField()),
                ('ssh_public_key', models.TextField()),
                ('beacon_consent', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_workspaces',
            },
            bases=(utils.mixins.models.AuditableModel, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', utils.delete.managers.SoftDeletionManager(alive_only=False)),
            ],
        ),
    ]
