# Generated by Django 3.0.10 on 2022-03-09 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='team_members',
            field=models.ManyToManyField(related_name='workspaces', through='authorization.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
