# Generated by Django 3.0.10 on 2022-03-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
        ('authentication', '0002_workspace_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='active_sso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sso.SSOConnection'),
        ),
    ]
