# Generated by Django 3.0.8 on 2020-07-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200707_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='beacon_consent',
            field=models.BooleanField(default=False),
        ),
    ]
