# Generated by Django 3.0.8 on 2020-08-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_workspace_beacon_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.CharField(default=None, max_length=128, null=True, unique=True),
        ),
    ]
