# Generated by Django 3.0.8 on 2020-08-26 15:14

from django.db import migrations, models
import django.db.models.manager
import utils.delete.managers


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_sub'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='workspace',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', utils.delete.managers.SoftDeletionManager(alive_only=False)),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
