version: '3.4'
x-metamapper-defaults: &metamapper_service
  image: metamapper:cypress
  depends_on:
    - database
    - redis
  environment:
    METAMAPPER_DB_HOST: database
    METAMAPPER_CELERY_BROKER_URL: "redis://redis:6379/0"
    METAMAPPER_CELERY_RESULT_BACKEND: "amqp"
    METAMAPPER_FERNET_KEY: mHYPeDvFJ1LtDClYGtckO-PZCBZfM2xLpWKqu7qQSkI=
services:
  redis:
    image: redis:3.0-alpine
    restart: unless-stopped
  database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metamapper
    restart: unless-stopped
  webserver:
    ipc: host
    build: ../
    command: ["./wait-for-it.sh", "database:5432", "--", "./bin/docker-entrypoint", "ci-webserver"]
    ports:
      - "5050:5050"
    << : *metamapper_service
  worker:
    ipc: host
    command: ["./wait-for-it.sh", "webserver:5050", "--", "./bin/docker-entrypoint", "worker"]
    depends_on:
      - webserver
    << : *metamapper_service
  cypress:
    ipc: host
    build:
      context: ../
      dockerfile: .circleci/Dockerfile.cypress
    environment:
      METAMAPPER_DB_HOST: database
      CYPRESS_baseUrl: "http://webserver:5050"
    volumes:
      - ./screenshots:/usr/src/app/www/cypress/screenshots/
