# Generated by Django 2.2.6 on 2020-06-07 03:15

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        TrigramExtension()
    ]
