# Generated by Django 3.2.12 on 2022-04-25 00:30

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import utils.delete.managers
import utils.shortcuts


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('definitions', '0004_alter_datastore_options'),
        ('authentication', '0005_user_user_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.CharField(db_index=True, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), default=list, size=None)),
                ('is_enabled', models.BooleanField(default=True)),
                ('short_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('interval', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('datastore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='definitions.datastore')),
            ],
            options={
                'db_table': 'checks',
            },
        ),
        migrations.CreateModel(
            name='CheckExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.BigIntegerField(default=utils.shortcuts.epoch_now)),
                ('tasks_count', models.IntegerField(default=0)),
                ('fails_count', models.IntegerField(default=0)),
                ('error', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(default=None, help_text='Timestamp for when the execution started', null=True)),
                ('finished_at', models.DateTimeField(default=None, help_text='Timestamp for when the execution finished', null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='checks.check')),
            ],
            options={
                'db_table': 'checks_execution',
            },
        ),
        migrations.CreateModel(
            name='CheckExpectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('handler_class', models.TextField()),
                ('handler_input', models.JSONField(default=dict)),
                ('pass_value_class', models.TextField()),
                ('pass_value_input', models.JSONField(default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectations', to='checks.check')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='authentication.workspace')),
            ],
            options={
                'db_table': 'checks_expectation',
            },
            managers=[
                ('objects', utils.delete.managers.SoftDeletionManager()),
                ('all_objects', utils.delete.managers.SoftDeletionManager(alive_only=False)),
            ],
        ),
        migrations.CreateModel(
            name='CheckQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(db_index=True, editable=False, max_length=32)),
                ('sql_text', models.TextField()),
                ('columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('datastore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='definitions.datastore')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='authentication.workspace')),
            ],
            options={
                'db_table': 'checks_query',
                'unique_together': {('key', 'workspace')},
            },
        ),
        migrations.CreateModel(
            name='CheckExpectationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.BigIntegerField(default=utils.shortcuts.epoch_now)),
                ('passed', models.BooleanField()),
                ('expected_value', models.BigIntegerField(null=True)),
                ('observed_value', models.BigIntegerField(null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectation_results', to='checks.checkexecution')),
                ('expectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='checks.checkexpectation')),
            ],
            options={
                'db_table': 'checks_expectationresult',
            },
        ),
        migrations.AddField(
            model_name='checkexecution',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='checks.checkquery'),
        ),
        migrations.AddField(
            model_name='checkexecution',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='authentication.workspace'),
        ),
        migrations.AddField(
            model_name='check',
            name='last_execution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='checks.checkexecution'),
        ),
        migrations.AddField(
            model_name='check',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='checks.checkquery'),
        ),
        migrations.AddField(
            model_name='check',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='authentication.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='checkexecution',
            unique_together={('job', 'epoch')},
        ),
    ]
