# Generated by Django 3.2.12 on 2022-05-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_user_permissions'),
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckAlertRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email')], max_length=15)),
                ('channel_config', models.JSONField(default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='checks.check')),
                ('last_failure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='checks.checkexecution')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='authentication.workspace')),
            ],
            options={
                'db_table': 'checks_alertrule',
            },
        ),
    ]
