# Generated by Django 3.2.12 on 2022-05-09 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_checkalertrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkalertrule',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
