# Generated by Django 3.2.12 on 2022-06-16 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_checkalertrule_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkexpectationresult',
            name='expectation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_results', to='checks.checkexpectation'),
        ),
    ]
