# Generated by Django 2.2.6 on 2020-05-26 16:38

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import utils.encrypt.fields
import utils.mixins.models
import utils.postgres.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.CharField(default=None, max_length=256, null=True)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('ordinal_position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data_type', models.CharField(max_length=255)),
                ('max_length', models.IntegerField(null=True)),
                ('numeric_scale', models.IntegerField(null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_nullable', models.BooleanField()),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('short_desc', models.CharField(blank=True, max_length=50)),
            ],
            bases=(utils.mixins.models.AuditableModel, models.Model),
        ),
        migrations.CreateModel(
            name='Datastore',
            fields=[
                ('id', models.CharField(db_index=True, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=300)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), default=list, size=None)),
                ('is_enabled', models.BooleanField(default=True)),
                ('version', models.CharField(max_length=255)),
                ('engine', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('sqlserver', 'SQL Server'), ('mysql', 'MySQL'), ('redshift', 'Redshift'), ('snowflake', 'Snowflake'), ('oracle', 'Oracle')], max_length=16)),
                ('host', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=128)),
                ('password', utils.encrypt.fields.EncryptedCharField(max_length=128)),
                ('database', models.CharField(max_length=128)),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65535)])),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('ssh_enabled', models.BooleanField(default=False)),
                ('ssh_host', models.CharField(max_length=128, null=True)),
                ('ssh_port', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(65535)])),
                ('ssh_user', models.CharField(max_length=128, null=True)),
                ('short_desc', models.CharField(blank=True, max_length=140)),
            ],
            bases=(utils.mixins.models.AuditableModel, models.Model),
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.CharField(default=None, max_length=256, null=True)),
                ('name', models.CharField(db_index=True, max_length=512)),
                ('kind', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('sql', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal_position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            managers=[
                ('objects', utils.postgres.managers.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.CharField(default=None, max_length=256, null=True)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), default=list, size=None)),
            ],
            bases=(utils.mixins.models.AuditableModel, models.Model),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.CharField(default=None, max_length=256, null=True)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), default=list, size=None)),
                ('kind', models.CharField(max_length=100)),
                ('short_desc', models.CharField(blank=True, max_length=140)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            bases=(utils.mixins.models.AuditableModel, models.Model),
        ),
    ]
