# Generated by Django 2.2.6 on 2020-05-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revisioner', '0001_initial'),
        ('authentication', '0003_workspace_active_sso'),
        ('definitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='created_revision',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='revisioner.Revision'),
        ),
        migrations.AddField(
            model_name='table',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='definitions.Schema'),
        ),
        migrations.AddField(
            model_name='table',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='authentication.Workspace'),
        ),
        migrations.AddField(
            model_name='schema',
            name='created_revision',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='revisioner.Revision'),
        ),
        migrations.AddField(
            model_name='schema',
            name='datastore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='definitions.Datastore'),
        ),
        migrations.AddField(
            model_name='schema',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='authentication.Workspace'),
        ),
        migrations.AddField(
            model_name='indexcolumn',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='definitions.Column'),
        ),
        migrations.AddField(
            model_name='indexcolumn',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_columns', to='definitions.Index'),
        ),
        migrations.AddField(
            model_name='indexcolumn',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='authentication.Workspace'),
        ),
        migrations.AddField(
            model_name='index',
            name='columns',
            field=models.ManyToManyField(through='definitions.IndexColumn', to='definitions.Column'),
        ),
        migrations.AddField(
            model_name='index',
            name='created_revision',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='revisioner.Revision'),
        ),
        migrations.AddField(
            model_name='index',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='definitions.Table'),
        ),
        migrations.AddField(
            model_name='index',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='authentication.Workspace'),
        ),
        migrations.AddField(
            model_name='datastore',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastores', to='authentication.Workspace'),
        ),
        migrations.AddField(
            model_name='column',
            name='created_revision',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='revisioner.Revision'),
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='definitions.Table'),
        ),
        migrations.AddField(
            model_name='column',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='authentication.Workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('schema', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='schema',
            unique_together={('datastore', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='indexcolumn',
            unique_together={('index', 'column', 'workspace')},
        ),
        migrations.AlterUniqueTogether(
            name='index',
            unique_together={('table', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='datastore',
            unique_together={('workspace', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('table', 'name')},
        ),
    ]
