# Generated by Django 3.2.13 on 2022-04-13 13:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0002_auto_20220413_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='incident_contacts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), default=list, size=None),
        ),
    ]
