# Generated by Django 3.2.12 on 2022-04-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0003_datastore_incident_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastore',
            options={'permissions': (('change_datastore_metadata', 'Change datastore metadata'), ('change_datastore_settings', 'Change datastore settings'), ('change_datastore_connection', 'Change datastore connection'), ('change_datastore_access', 'Change datastore access'), ('change_datastore_checks', 'Change datastore checks'), ('comment_on_datastore', 'Comment on datastore'))},
        ),
    ]
