# Generated by Django 3.2.12 on 2022-05-20 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0004_alter_datastore_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
