# Generated by Django 3.0.8 on 2020-07-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0004_auto_20200625_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableProperty',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('value', models.TextField(db_column='property_value')),
            ],
            options={
                'db_table': 'definitions_table_properties',
                'managed': False,
            },
        ),
    ]
