# Generated by Django 3.2.12 on 2022-06-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0005_datastore_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('db_schema', models.CharField(max_length=256)),
                ('db_table', models.CharField(max_length=256)),
                ('db_user', models.CharField(max_length=256)),
                ('queries_seen', models.IntegerField(default=0)),
                ('datastore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='definitions.datastore')),
            ],
            options={
                'db_table': 'definitions_table_usage',
                'unique_together': {('date', 'datastore', 'db_schema', 'db_table', 'db_user')},
                'index_together': {('datastore', 'db_schema', 'db_table')},
            },
        ),
    ]
