# Generated by Django 3.0.8 on 2020-07-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0005_tableproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastore',
            options={'permissions': (('change_datastore_metadata', 'Change datastore metadata'), ('change_datastore_settings', 'Change datastore settings'), ('change_datastore_connection', 'Change datastore connection'), ('comment_on_datastore', 'Comment on datastore'))},
        ),
        migrations.AddField(
            model_name='datastore',
            name='object_permissions_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
