# Generated by Django 3.0.8 on 2020-07-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0006_auto_20200709_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastore',
            options={'permissions': (('change_datastore_metadata', 'Change datastore metadata'), ('change_datastore_settings', 'Change datastore settings'), ('change_datastore_connection', 'Change datastore connection'), ('change_datastore_access', 'Change datastore access'), ('comment_on_datastore', 'Comment on datastore'))},
        ),
    ]
