# Generated by Django 3.2.12 on 2022-07-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0006_auto_20220630_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='slug',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
