# Generated by Django 3.2.12 on 2022-06-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0006_auto_20220630_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableUsageExists',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'definitions_table_usage_exists',
            },
        ),
    ]
