# Generated by Django 3.2.12 on 2022-06-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0006_tableusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableusage',
            old_name='date',
            new_name='execution_date',
        ),
        migrations.RenameField(
            model_name='tableusage',
            old_name='queries_seen',
            new_name='query_count',
        ),
        migrations.AddField(
            model_name='datastore',
            name='usage_last_synced_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tableusage',
            unique_together={('execution_date', 'datastore', 'db_schema', 'db_table', 'db_user')},
        ),
    ]
