# Generated by Django 3.0.8 on 2020-08-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0007_auto_20200715_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
