# Generated by Django 3.2.12 on 2022-07-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0006_assetowner_classification'),
        ('definitions', '0006_auto_20220630_2210'),
        ('definitions', '0007_alter_datastore_slug'),
    ]

    operations = [
    ]
