# Generated by Django 3.0.8 on 2020-08-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0009_auto_20200812_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='object_id',
            field=models.CharField(db_index=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='object_id',
            field=models.CharField(db_index=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='object_id',
            field=models.CharField(db_index=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='object_id',
            field=models.CharField(db_index=True, default=None, max_length=256, null=True),
        ),
    ]
