# Generated by Django 3.0.8 on 2020-08-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0010_auto_20200817_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='created_revision_id',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='created_revision_id',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='created_revision_id',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='created_revision_id',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
