# Generated by Django 3.0.8 on 2020-08-18 04:58

from django.db import migrations
import django.db.models.manager
import utils.delete.managers


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0011_auto_20200818_0147'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='schema',
            managers=[
                ('search_objects', django.db.models.manager.Manager()),
                ('objects', utils.delete.managers.SoftDeletionManager()),
                ('all_objects', utils.delete.managers.SoftDeletionManager(alive_only=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name='table',
            managers=[
                ('search_objects', django.db.models.manager.Manager()),
                ('objects', utils.delete.managers.SoftDeletionManager()),
                ('all_objects', utils.delete.managers.SoftDeletionManager(alive_only=False)),
            ],
        ),
    ]
