# Generated by Django 3.0.8 on 2020-08-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0013_auto_20200819_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='engine',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('sqlserver', 'SQL Server'), ('mysql', 'MySQL'), ('redshift', 'Redshift'), ('snowflake', 'Snowflake'), ('oracle', 'Oracle'), ('bigquery', 'Google BigQuery'), ('athena', 'AWS Athena'), ('glue', 'AWS Glue'), ('azure_sql', 'Azure SQL Database'), ('azure_dwh', 'Azure Synapse'), ('hive', 'Hive Metastore')], max_length=16),
        ),
    ]
