# Generated by Django 3.0.8 on 2020-08-26 01:59

from django.db import migrations, models
import django.db.models.manager
import utils.delete.managers


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0013_auto_20200819_1624'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='datastore',
            managers=[
                ('search_objects', django.db.models.manager.Manager()),
                ('objects', utils.delete.managers.SoftDeletionManager()),
                ('all_objects', utils.delete.managers.SoftDeletionManager(alive_only=False)),
            ],
        ),
        migrations.AddField(
            model_name='datastore',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
