# Generated by Django 3.0.8 on 2020-08-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0014_auto_20200826_0159'),
        ('definitions', '0014_auto_20200828_2056'),
    ]

    operations = [
    ]
