# Generated by Django 3.0.8 on 2020-09-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0015_merge_20200828_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='comment',
            new_name='db_comment',
        ),
        migrations.AddField(
            model_name='table',
            name='db_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
