# Generated by Django 3.0.8 on 2020-09-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0016_auto_20200901_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
