# Generated by Django 3.0.10 on 2021-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0019_auto_20201019_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='object_id',
            field=models.CharField(db_index=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='object_id',
            field=models.CharField(db_index=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='object_id',
            field=models.CharField(db_index=True, default=None, max_length=40, null=True),
        ),
    ]
