# Generated by Django 3.0.10 on 2021-10-20 18:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0020_auto_20210522_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), default=list, size=None),
        ),
    ]
