# Generated by Django 3.0.7 on 2020-06-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('ts', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
    ]
