# Generated by Django 3.0.10 on 2022-03-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('ts', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
    ]
