# Generated by Django 3.0.10 on 2020-10-22 17:12

from django.db import connection, migrations
from django.core.management import call_command


def forwards_func(apps, schema_editor):
    call_command('createcachetable', 'django_db_cache')


def reverse_func(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute('DROP TABLE django_db_cache')


class Migration(migrations.Migration):

    dependencies = [
        ('healthchecks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
