# Generated by Django 3.0.8 on 2020-08-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customfields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('USER', 'User'), ('TEXT', 'Text'), ('ENUM', 'Enum'), ('GROUP', 'Group')], max_length=30),
        ),
    ]
