# Generated by Django 2.2.6 on 2020-05-26 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.mixins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.CharField(choices=[('OWNER', 'Administrator (Owner)'), ('MEMBER', 'Member'), ('READONLY', 'Readonly')], default='MEMBER', help_text='Global access permissions for the workspace.', max_length=10)),
                ('user', models.ForeignKey(db_column='email', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='authentication.Workspace')),
            ],
            options={
                'db_table': 'auth_memberships',
                'unique_together': {('workspace', 'user')},
            },
            bases=(models.Model, utils.mixins.models.AuditableModel),
        ),
    ]
