# Generated by Django 3.0.8 on 2020-07-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20200713_1842'),
        ('authorization', '0001_initial'),
    ]

    operations = [
    ]
